[package]
name = "guest"
version = "0.1.0"
edition = "2021"

[dependencies]
runtime = { path = "../../../../runtime" }
macros = { path = "../../../../macros" }
sha2 = { version = "0.10.8", default-features = false}