use poulpy_schemes::tfhe::bdd_arithmetic::{
    BitCircuit, BitCircuitFamily, BitCircuitInfo, Circuit, Node,
};
pub(crate) enum AnyBitCircuit {
    B0(BitCircuit<2>),
    B1(BitCircuit<2>),
    B2(BitCircuit<2>),
    B3(BitCircuit<4>),
    B4(BitCircuit<6>),
    B5(BitCircuit<8>),
    B6(BitCircuit<10>),
    B7(BitCircuit<12>),
    B8(BitCircuit<14>),
    B9(BitCircuit<16>),
    B10(BitCircuit<18>),
    B11(BitCircuit<20>),
    B12(BitCircuit<22>),
    B13(BitCircuit<24>),
    B14(BitCircuit<26>),
    B15(BitCircuit<28>),
    B16(BitCircuit<30>),
    B17(BitCircuit<32>),
    B18(BitCircuit<34>),
    B19(BitCircuit<36>),
    B20(BitCircuit<38>),
    B21(BitCircuit<40>),
    B22(BitCircuit<42>),
    B23(BitCircuit<44>),
    B24(BitCircuit<46>),
    B25(BitCircuit<48>),
    B26(BitCircuit<50>),
    B27(BitCircuit<52>),
    B28(BitCircuit<54>),
    B29(BitCircuit<56>),
    B30(BitCircuit<58>),
    B31(BitCircuit<60>),
}
impl BitCircuitInfo for AnyBitCircuit {
    fn info(&self) -> (&[Node], usize) {
        match self {
            AnyBitCircuit::B0(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B1(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B2(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B3(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B4(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B5(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B6(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B7(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B8(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B9(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B10(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B11(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B12(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B13(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B14(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B15(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B16(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B17(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B18(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B19(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B20(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B21(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B22(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B23(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B24(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B25(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B26(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B27(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B28(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B29(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B30(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
            AnyBitCircuit::B31(bit_circuit) => {
                (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state)
            }
        }
    }
}

impl BitCircuitFamily for AnyBitCircuit {
    const INPUT_BITS: usize = 32;
    const OUTPUT_BITS: usize = 32;
}

pub(crate) static OUTPUT_CIRCUITS: Circuit<AnyBitCircuit, 32usize> = Circuit([
    AnyBitCircuit::B0(BitCircuit::new([Node::Cmux(0, 1, 0), Node::None], 2)),
    AnyBitCircuit::B1(BitCircuit::new([Node::Cmux(1, 1, 0), Node::None], 2)),
    AnyBitCircuit::B2(BitCircuit::new([Node::Cmux(2, 0, 1), Node::None], 2)),
    AnyBitCircuit::B3(BitCircuit::new(
        [
            Node::Cmux(3, 0, 1),
            Node::Cmux(3, 1, 0),
            Node::Cmux(2, 0, 1),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B4(BitCircuit::new(
        [
            Node::Cmux(4, 0, 1),
            Node::Cmux(4, 1, 0),
            Node::Cmux(3, 0, 1),
            Node::Copy,
            Node::Cmux(2, 0, 1),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B5(BitCircuit::new(
        [
            Node::Cmux(5, 0, 1),
            Node::Cmux(5, 1, 0),
            Node::Cmux(4, 0, 1),
            Node::Copy,
            Node::Cmux(3, 0, 1),
            Node::Copy,
            Node::Cmux(2, 0, 1),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B6(BitCircuit::new(
        [
            Node::Cmux(6, 0, 1),
            Node::Cmux(6, 1, 0),
            Node::Cmux(5, 0, 1),
            Node::Copy,
            Node::Cmux(4, 0, 1),
            Node::Copy,
            Node::Cmux(3, 0, 1),
            Node::Copy,
            Node::Cmux(2, 0, 1),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B7(BitCircuit::new(
        [
            Node::Cmux(7, 0, 1),
            Node::Cmux(7, 1, 0),
            Node::Cmux(6, 0, 1),
            Node::Copy,
            Node::Cmux(5, 0, 1),
            Node::Copy,
            Node::Cmux(4, 0, 1),
            Node::Copy,
            Node::Cmux(3, 0, 1),
            Node::Copy,
            Node::Cmux(2, 0, 1),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B8(BitCircuit::new(
        [
            Node::Cmux(8, 1, 0),
            Node::Cmux(8, 0, 1),
            Node::Copy,
            Node::Cmux(7, 1, 0),
            Node::Copy,
            Node::Cmux(6, 1, 0),
            Node::Copy,
            Node::Cmux(5, 1, 0),
            Node::Copy,
            Node::Cmux(4, 1, 0),
            Node::Copy,
            Node::Cmux(3, 1, 0),
            Node::Cmux(2, 1, 0),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B9(BitCircuit::new(
        [
            Node::Cmux(9, 0, 1),
            Node::Cmux(9, 1, 0),
            Node::Cmux(8, 0, 1),
            Node::Copy,
            Node::Cmux(7, 0, 1),
            Node::Copy,
            Node::Cmux(6, 0, 1),
            Node::Copy,
            Node::Cmux(5, 0, 1),
            Node::Copy,
            Node::Cmux(4, 0, 1),
            Node::Copy,
            Node::Cmux(3, 0, 1),
            Node::Copy,
            Node::Cmux(2, 0, 1),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B10(BitCircuit::new(
        [
            Node::Cmux(10, 0, 1),
            Node::Cmux(10, 1, 0),
            Node::Cmux(9, 0, 1),
            Node::Copy,
            Node::Cmux(8, 0, 1),
            Node::Copy,
            Node::Cmux(7, 0, 1),
            Node::Copy,
            Node::Cmux(6, 0, 1),
            Node::Copy,
            Node::Cmux(5, 0, 1),
            Node::Copy,
            Node::Cmux(4, 0, 1),
            Node::Copy,
            Node::Cmux(3, 0, 1),
            Node::Copy,
            Node::Cmux(2, 0, 1),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B11(BitCircuit::new(
        [
            Node::Cmux(11, 0, 1),
            Node::Cmux(11, 1, 0),
            Node::Cmux(10, 0, 1),
            Node::Copy,
            Node::Cmux(9, 0, 1),
            Node::Copy,
            Node::Cmux(8, 0, 1),
            Node::Copy,
            Node::Cmux(7, 0, 1),
            Node::Copy,
            Node::Cmux(6, 0, 1),
            Node::Copy,
            Node::Cmux(5, 0, 1),
            Node::Copy,
            Node::Cmux(4, 0, 1),
            Node::Copy,
            Node::Cmux(3, 0, 1),
            Node::Copy,
            Node::Cmux(2, 0, 1),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B12(BitCircuit::new(
        [
            Node::Cmux(12, 0, 1),
            Node::Cmux(12, 1, 0),
            Node::Cmux(11, 0, 1),
            Node::Copy,
            Node::Cmux(10, 0, 1),
            Node::Copy,
            Node::Cmux(9, 0, 1),
            Node::Copy,
            Node::Cmux(8, 0, 1),
            Node::Copy,
            Node::Cmux(7, 0, 1),
            Node::Copy,
            Node::Cmux(6, 0, 1),
            Node::Copy,
            Node::Cmux(5, 0, 1),
            Node::Copy,
            Node::Cmux(4, 0, 1),
            Node::Copy,
            Node::Cmux(3, 0, 1),
            Node::Copy,
            Node::Cmux(2, 0, 1),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B13(BitCircuit::new(
        [
            Node::Cmux(13, 1, 0),
            Node::Cmux(13, 0, 1),
            Node::Copy,
            Node::Cmux(12, 1, 0),
            Node::Copy,
            Node::Cmux(11, 1, 0),
            Node::Copy,
            Node::Cmux(10, 1, 0),
            Node::Copy,
            Node::Cmux(9, 1, 0),
            Node::Copy,
            Node::Cmux(8, 1, 0),
            Node::Copy,
            Node::Cmux(7, 1, 0),
            Node::Copy,
            Node::Cmux(6, 1, 0),
            Node::Copy,
            Node::Cmux(5, 1, 0),
            Node::Copy,
            Node::Cmux(4, 1, 0),
            Node::Copy,
            Node::Cmux(3, 1, 0),
            Node::Cmux(2, 1, 0),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B14(BitCircuit::new(
        [
            Node::Cmux(14, 0, 1),
            Node::Cmux(14, 1, 0),
            Node::Cmux(13, 0, 1),
            Node::Copy,
            Node::Cmux(12, 0, 1),
            Node::Copy,
            Node::Cmux(11, 0, 1),
            Node::Copy,
            Node::Cmux(10, 0, 1),
            Node::Copy,
            Node::Cmux(9, 0, 1),
            Node::Copy,
            Node::Cmux(8, 0, 1),
            Node::Copy,
            Node::Cmux(7, 0, 1),
            Node::Copy,
            Node::Cmux(6, 0, 1),
            Node::Copy,
            Node::Cmux(5, 0, 1),
            Node::Copy,
            Node::Cmux(4, 0, 1),
            Node::Copy,
            Node::Cmux(3, 0, 1),
            Node::Copy,
            Node::Cmux(2, 0, 1),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B15(BitCircuit::new(
        [
            Node::Cmux(15, 0, 1),
            Node::Cmux(15, 1, 0),
            Node::Cmux(14, 0, 1),
            Node::Copy,
            Node::Cmux(13, 0, 1),
            Node::Copy,
            Node::Cmux(12, 0, 1),
            Node::Copy,
            Node::Cmux(11, 0, 1),
            Node::Copy,
            Node::Cmux(10, 0, 1),
            Node::Copy,
            Node::Cmux(9, 0, 1),
            Node::Copy,
            Node::Cmux(8, 0, 1),
            Node::Copy,
            Node::Cmux(7, 0, 1),
            Node::Copy,
            Node::Cmux(6, 0, 1),
            Node::Copy,
            Node::Cmux(5, 0, 1),
            Node::Copy,
            Node::Cmux(4, 0, 1),
            Node::Copy,
            Node::Cmux(3, 0, 1),
            Node::Copy,
            Node::Cmux(2, 0, 1),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B16(BitCircuit::new(
        [
            Node::Cmux(16, 0, 1),
            Node::Cmux(16, 1, 0),
            Node::Cmux(15, 0, 1),
            Node::Copy,
            Node::Cmux(14, 0, 1),
            Node::Copy,
            Node::Cmux(13, 0, 1),
            Node::Copy,
            Node::Cmux(12, 0, 1),
            Node::Copy,
            Node::Cmux(11, 0, 1),
            Node::Copy,
            Node::Cmux(10, 0, 1),
            Node::Copy,
            Node::Cmux(9, 0, 1),
            Node::Copy,
            Node::Cmux(8, 0, 1),
            Node::Copy,
            Node::Cmux(7, 0, 1),
            Node::Copy,
            Node::Cmux(6, 0, 1),
            Node::Copy,
            Node::Cmux(5, 0, 1),
            Node::Copy,
            Node::Cmux(4, 0, 1),
            Node::Copy,
            Node::Cmux(3, 0, 1),
            Node::Copy,
            Node::Cmux(2, 0, 1),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B17(BitCircuit::new(
        [
            Node::Cmux(17, 1, 0),
            Node::Cmux(17, 0, 1),
            Node::Copy,
            Node::Cmux(16, 1, 0),
            Node::Copy,
            Node::Cmux(15, 1, 0),
            Node::Copy,
            Node::Cmux(14, 1, 0),
            Node::Copy,
            Node::Cmux(13, 1, 0),
            Node::Copy,
            Node::Cmux(12, 1, 0),
            Node::Copy,
            Node::Cmux(11, 1, 0),
            Node::Copy,
            Node::Cmux(10, 1, 0),
            Node::Copy,
            Node::Cmux(9, 1, 0),
            Node::Copy,
            Node::Cmux(8, 1, 0),
            Node::Copy,
            Node::Cmux(7, 1, 0),
            Node::Copy,
            Node::Cmux(6, 1, 0),
            Node::Copy,
            Node::Cmux(5, 1, 0),
            Node::Copy,
            Node::Cmux(4, 1, 0),
            Node::Copy,
            Node::Cmux(3, 1, 0),
            Node::Cmux(2, 1, 0),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B18(BitCircuit::new(
        [
            Node::Cmux(18, 0, 1),
            Node::Cmux(18, 1, 0),
            Node::Cmux(17, 0, 1),
            Node::Copy,
            Node::Cmux(16, 0, 1),
            Node::Copy,
            Node::Cmux(15, 0, 1),
            Node::Copy,
            Node::Cmux(14, 0, 1),
            Node::Copy,
            Node::Cmux(13, 0, 1),
            Node::Copy,
            Node::Cmux(12, 0, 1),
            Node::Copy,
            Node::Cmux(11, 0, 1),
            Node::Copy,
            Node::Cmux(10, 0, 1),
            Node::Copy,
            Node::Cmux(9, 0, 1),
            Node::Copy,
            Node::Cmux(8, 0, 1),
            Node::Copy,
            Node::Cmux(7, 0, 1),
            Node::Copy,
            Node::Cmux(6, 0, 1),
            Node::Copy,
            Node::Cmux(5, 0, 1),
            Node::Copy,
            Node::Cmux(4, 0, 1),
            Node::Copy,
            Node::Cmux(3, 0, 1),
            Node::Copy,
            Node::Cmux(2, 0, 1),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B19(BitCircuit::new(
        [
            Node::Cmux(19, 1, 0),
            Node::Cmux(19, 0, 1),
            Node::Copy,
            Node::Cmux(18, 1, 0),
            Node::Copy,
            Node::Cmux(17, 1, 0),
            Node::Copy,
            Node::Cmux(16, 1, 0),
            Node::Copy,
            Node::Cmux(15, 1, 0),
            Node::Copy,
            Node::Cmux(14, 1, 0),
            Node::Copy,
            Node::Cmux(13, 1, 0),
            Node::Copy,
            Node::Cmux(12, 1, 0),
            Node::Copy,
            Node::Cmux(11, 1, 0),
            Node::Copy,
            Node::Cmux(10, 1, 0),
            Node::Copy,
            Node::Cmux(9, 1, 0),
            Node::Copy,
            Node::Cmux(8, 1, 0),
            Node::Copy,
            Node::Cmux(7, 1, 0),
            Node::Copy,
            Node::Cmux(6, 1, 0),
            Node::Copy,
            Node::Cmux(5, 1, 0),
            Node::Copy,
            Node::Cmux(4, 1, 0),
            Node::Copy,
            Node::Cmux(3, 1, 0),
            Node::Cmux(2, 1, 0),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B20(BitCircuit::new(
        [
            Node::Cmux(20, 1, 0),
            Node::Cmux(20, 0, 1),
            Node::Copy,
            Node::Cmux(19, 1, 0),
            Node::Copy,
            Node::Cmux(18, 1, 0),
            Node::Copy,
            Node::Cmux(17, 1, 0),
            Node::Copy,
            Node::Cmux(16, 1, 0),
            Node::Copy,
            Node::Cmux(15, 1, 0),
            Node::Copy,
            Node::Cmux(14, 1, 0),
            Node::Copy,
            Node::Cmux(13, 1, 0),
            Node::Copy,
            Node::Cmux(12, 1, 0),
            Node::Copy,
            Node::Cmux(11, 1, 0),
            Node::Copy,
            Node::Cmux(10, 1, 0),
            Node::Copy,
            Node::Cmux(9, 1, 0),
            Node::Copy,
            Node::Cmux(8, 1, 0),
            Node::Copy,
            Node::Cmux(7, 1, 0),
            Node::Copy,
            Node::Cmux(6, 1, 0),
            Node::Copy,
            Node::Cmux(5, 1, 0),
            Node::Copy,
            Node::Cmux(4, 1, 0),
            Node::Copy,
            Node::Cmux(3, 1, 0),
            Node::Cmux(2, 1, 0),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B21(BitCircuit::new(
        [
            Node::Cmux(21, 1, 0),
            Node::Cmux(21, 0, 1),
            Node::Copy,
            Node::Cmux(20, 1, 0),
            Node::Copy,
            Node::Cmux(19, 1, 0),
            Node::Copy,
            Node::Cmux(18, 1, 0),
            Node::Copy,
            Node::Cmux(17, 1, 0),
            Node::Copy,
            Node::Cmux(16, 1, 0),
            Node::Copy,
            Node::Cmux(15, 1, 0),
            Node::Copy,
            Node::Cmux(14, 1, 0),
            Node::Copy,
            Node::Cmux(13, 1, 0),
            Node::Copy,
            Node::Cmux(12, 1, 0),
            Node::Copy,
            Node::Cmux(11, 1, 0),
            Node::Copy,
            Node::Cmux(10, 1, 0),
            Node::Copy,
            Node::Cmux(9, 1, 0),
            Node::Copy,
            Node::Cmux(8, 1, 0),
            Node::Copy,
            Node::Cmux(7, 1, 0),
            Node::Copy,
            Node::Cmux(6, 1, 0),
            Node::Copy,
            Node::Cmux(5, 1, 0),
            Node::Copy,
            Node::Cmux(4, 1, 0),
            Node::Copy,
            Node::Cmux(3, 1, 0),
            Node::Cmux(2, 1, 0),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B22(BitCircuit::new(
        [
            Node::Cmux(22, 1, 0),
            Node::Cmux(22, 0, 1),
            Node::Copy,
            Node::Cmux(21, 1, 0),
            Node::Copy,
            Node::Cmux(20, 1, 0),
            Node::Copy,
            Node::Cmux(19, 1, 0),
            Node::Copy,
            Node::Cmux(18, 1, 0),
            Node::Copy,
            Node::Cmux(17, 1, 0),
            Node::Copy,
            Node::Cmux(16, 1, 0),
            Node::Copy,
            Node::Cmux(15, 1, 0),
            Node::Copy,
            Node::Cmux(14, 1, 0),
            Node::Copy,
            Node::Cmux(13, 1, 0),
            Node::Copy,
            Node::Cmux(12, 1, 0),
            Node::Copy,
            Node::Cmux(11, 1, 0),
            Node::Copy,
            Node::Cmux(10, 1, 0),
            Node::Copy,
            Node::Cmux(9, 1, 0),
            Node::Copy,
            Node::Cmux(8, 1, 0),
            Node::Copy,
            Node::Cmux(7, 1, 0),
            Node::Copy,
            Node::Cmux(6, 1, 0),
            Node::Copy,
            Node::Cmux(5, 1, 0),
            Node::Copy,
            Node::Cmux(4, 1, 0),
            Node::Copy,
            Node::Cmux(3, 1, 0),
            Node::Cmux(2, 1, 0),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B23(BitCircuit::new(
        [
            Node::Cmux(23, 1, 0),
            Node::Cmux(23, 0, 1),
            Node::Copy,
            Node::Cmux(22, 1, 0),
            Node::Copy,
            Node::Cmux(21, 1, 0),
            Node::Copy,
            Node::Cmux(20, 1, 0),
            Node::Copy,
            Node::Cmux(19, 1, 0),
            Node::Copy,
            Node::Cmux(18, 1, 0),
            Node::Copy,
            Node::Cmux(17, 1, 0),
            Node::Copy,
            Node::Cmux(16, 1, 0),
            Node::Copy,
            Node::Cmux(15, 1, 0),
            Node::Copy,
            Node::Cmux(14, 1, 0),
            Node::Copy,
            Node::Cmux(13, 1, 0),
            Node::Copy,
            Node::Cmux(12, 1, 0),
            Node::Copy,
            Node::Cmux(11, 1, 0),
            Node::Copy,
            Node::Cmux(10, 1, 0),
            Node::Copy,
            Node::Cmux(9, 1, 0),
            Node::Copy,
            Node::Cmux(8, 1, 0),
            Node::Copy,
            Node::Cmux(7, 1, 0),
            Node::Copy,
            Node::Cmux(6, 1, 0),
            Node::Copy,
            Node::Cmux(5, 1, 0),
            Node::Copy,
            Node::Cmux(4, 1, 0),
            Node::Copy,
            Node::Cmux(3, 1, 0),
            Node::Cmux(2, 1, 0),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B24(BitCircuit::new(
        [
            Node::Cmux(24, 1, 0),
            Node::Cmux(24, 0, 1),
            Node::Copy,
            Node::Cmux(23, 1, 0),
            Node::Copy,
            Node::Cmux(22, 1, 0),
            Node::Copy,
            Node::Cmux(21, 1, 0),
            Node::Copy,
            Node::Cmux(20, 1, 0),
            Node::Copy,
            Node::Cmux(19, 1, 0),
            Node::Copy,
            Node::Cmux(18, 1, 0),
            Node::Copy,
            Node::Cmux(17, 1, 0),
            Node::Copy,
            Node::Cmux(16, 1, 0),
            Node::Copy,
            Node::Cmux(15, 1, 0),
            Node::Copy,
            Node::Cmux(14, 1, 0),
            Node::Copy,
            Node::Cmux(13, 1, 0),
            Node::Copy,
            Node::Cmux(12, 1, 0),
            Node::Copy,
            Node::Cmux(11, 1, 0),
            Node::Copy,
            Node::Cmux(10, 1, 0),
            Node::Copy,
            Node::Cmux(9, 1, 0),
            Node::Copy,
            Node::Cmux(8, 1, 0),
            Node::Copy,
            Node::Cmux(7, 1, 0),
            Node::Copy,
            Node::Cmux(6, 1, 0),
            Node::Copy,
            Node::Cmux(5, 1, 0),
            Node::Copy,
            Node::Cmux(4, 1, 0),
            Node::Copy,
            Node::Cmux(3, 1, 0),
            Node::Cmux(2, 1, 0),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B25(BitCircuit::new(
        [
            Node::Cmux(25, 0, 1),
            Node::Cmux(25, 1, 0),
            Node::Cmux(24, 0, 1),
            Node::Copy,
            Node::Cmux(23, 0, 1),
            Node::Copy,
            Node::Cmux(22, 0, 1),
            Node::Copy,
            Node::Cmux(21, 0, 1),
            Node::Copy,
            Node::Cmux(20, 0, 1),
            Node::Copy,
            Node::Cmux(19, 0, 1),
            Node::Copy,
            Node::Cmux(18, 0, 1),
            Node::Copy,
            Node::Cmux(17, 0, 1),
            Node::Copy,
            Node::Cmux(16, 0, 1),
            Node::Copy,
            Node::Cmux(15, 0, 1),
            Node::Copy,
            Node::Cmux(14, 0, 1),
            Node::Copy,
            Node::Cmux(13, 0, 1),
            Node::Copy,
            Node::Cmux(12, 0, 1),
            Node::Copy,
            Node::Cmux(11, 0, 1),
            Node::Copy,
            Node::Cmux(10, 0, 1),
            Node::Copy,
            Node::Cmux(9, 0, 1),
            Node::Copy,
            Node::Cmux(8, 0, 1),
            Node::Copy,
            Node::Cmux(7, 0, 1),
            Node::Copy,
            Node::Cmux(6, 0, 1),
            Node::Copy,
            Node::Cmux(5, 0, 1),
            Node::Copy,
            Node::Cmux(4, 0, 1),
            Node::Copy,
            Node::Cmux(3, 0, 1),
            Node::Copy,
            Node::Cmux(2, 0, 1),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B26(BitCircuit::new(
        [
            Node::Cmux(26, 0, 1),
            Node::Cmux(26, 1, 0),
            Node::Cmux(25, 0, 1),
            Node::Copy,
            Node::Cmux(24, 0, 1),
            Node::Copy,
            Node::Cmux(23, 0, 1),
            Node::Copy,
            Node::Cmux(22, 0, 1),
            Node::Copy,
            Node::Cmux(21, 0, 1),
            Node::Copy,
            Node::Cmux(20, 0, 1),
            Node::Copy,
            Node::Cmux(19, 0, 1),
            Node::Copy,
            Node::Cmux(18, 0, 1),
            Node::Copy,
            Node::Cmux(17, 0, 1),
            Node::Copy,
            Node::Cmux(16, 0, 1),
            Node::Copy,
            Node::Cmux(15, 0, 1),
            Node::Copy,
            Node::Cmux(14, 0, 1),
            Node::Copy,
            Node::Cmux(13, 0, 1),
            Node::Copy,
            Node::Cmux(12, 0, 1),
            Node::Copy,
            Node::Cmux(11, 0, 1),
            Node::Copy,
            Node::Cmux(10, 0, 1),
            Node::Copy,
            Node::Cmux(9, 0, 1),
            Node::Copy,
            Node::Cmux(8, 0, 1),
            Node::Copy,
            Node::Cmux(7, 0, 1),
            Node::Copy,
            Node::Cmux(6, 0, 1),
            Node::Copy,
            Node::Cmux(5, 0, 1),
            Node::Copy,
            Node::Cmux(4, 0, 1),
            Node::Copy,
            Node::Cmux(3, 0, 1),
            Node::Copy,
            Node::Cmux(2, 0, 1),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B27(BitCircuit::new(
        [
            Node::Cmux(27, 0, 1),
            Node::Cmux(27, 1, 0),
            Node::Cmux(26, 0, 1),
            Node::Copy,
            Node::Cmux(25, 0, 1),
            Node::Copy,
            Node::Cmux(24, 0, 1),
            Node::Copy,
            Node::Cmux(23, 0, 1),
            Node::Copy,
            Node::Cmux(22, 0, 1),
            Node::Copy,
            Node::Cmux(21, 0, 1),
            Node::Copy,
            Node::Cmux(20, 0, 1),
            Node::Copy,
            Node::Cmux(19, 0, 1),
            Node::Copy,
            Node::Cmux(18, 0, 1),
            Node::Copy,
            Node::Cmux(17, 0, 1),
            Node::Copy,
            Node::Cmux(16, 0, 1),
            Node::Copy,
            Node::Cmux(15, 0, 1),
            Node::Copy,
            Node::Cmux(14, 0, 1),
            Node::Copy,
            Node::Cmux(13, 0, 1),
            Node::Copy,
            Node::Cmux(12, 0, 1),
            Node::Copy,
            Node::Cmux(11, 0, 1),
            Node::Copy,
            Node::Cmux(10, 0, 1),
            Node::Copy,
            Node::Cmux(9, 0, 1),
            Node::Copy,
            Node::Cmux(8, 0, 1),
            Node::Copy,
            Node::Cmux(7, 0, 1),
            Node::Copy,
            Node::Cmux(6, 0, 1),
            Node::Copy,
            Node::Cmux(5, 0, 1),
            Node::Copy,
            Node::Cmux(4, 0, 1),
            Node::Copy,
            Node::Cmux(3, 0, 1),
            Node::Copy,
            Node::Cmux(2, 0, 1),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B28(BitCircuit::new(
        [
            Node::Cmux(28, 0, 1),
            Node::Cmux(28, 1, 0),
            Node::Cmux(27, 0, 1),
            Node::Copy,
            Node::Cmux(26, 0, 1),
            Node::Copy,
            Node::Cmux(25, 0, 1),
            Node::Copy,
            Node::Cmux(24, 0, 1),
            Node::Copy,
            Node::Cmux(23, 0, 1),
            Node::Copy,
            Node::Cmux(22, 0, 1),
            Node::Copy,
            Node::Cmux(21, 0, 1),
            Node::Copy,
            Node::Cmux(20, 0, 1),
            Node::Copy,
            Node::Cmux(19, 0, 1),
            Node::Copy,
            Node::Cmux(18, 0, 1),
            Node::Copy,
            Node::Cmux(17, 0, 1),
            Node::Copy,
            Node::Cmux(16, 0, 1),
            Node::Copy,
            Node::Cmux(15, 0, 1),
            Node::Copy,
            Node::Cmux(14, 0, 1),
            Node::Copy,
            Node::Cmux(13, 0, 1),
            Node::Copy,
            Node::Cmux(12, 0, 1),
            Node::Copy,
            Node::Cmux(11, 0, 1),
            Node::Copy,
            Node::Cmux(10, 0, 1),
            Node::Copy,
            Node::Cmux(9, 0, 1),
            Node::Copy,
            Node::Cmux(8, 0, 1),
            Node::Copy,
            Node::Cmux(7, 0, 1),
            Node::Copy,
            Node::Cmux(6, 0, 1),
            Node::Copy,
            Node::Cmux(5, 0, 1),
            Node::Copy,
            Node::Cmux(4, 0, 1),
            Node::Copy,
            Node::Cmux(3, 0, 1),
            Node::Copy,
            Node::Cmux(2, 0, 1),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B29(BitCircuit::new(
        [
            Node::Cmux(29, 0, 1),
            Node::Cmux(29, 1, 0),
            Node::Cmux(28, 0, 1),
            Node::Copy,
            Node::Cmux(27, 0, 1),
            Node::Copy,
            Node::Cmux(26, 0, 1),
            Node::Copy,
            Node::Cmux(25, 0, 1),
            Node::Copy,
            Node::Cmux(24, 0, 1),
            Node::Copy,
            Node::Cmux(23, 0, 1),
            Node::Copy,
            Node::Cmux(22, 0, 1),
            Node::Copy,
            Node::Cmux(21, 0, 1),
            Node::Copy,
            Node::Cmux(20, 0, 1),
            Node::Copy,
            Node::Cmux(19, 0, 1),
            Node::Copy,
            Node::Cmux(18, 0, 1),
            Node::Copy,
            Node::Cmux(17, 0, 1),
            Node::Copy,
            Node::Cmux(16, 0, 1),
            Node::Copy,
            Node::Cmux(15, 0, 1),
            Node::Copy,
            Node::Cmux(14, 0, 1),
            Node::Copy,
            Node::Cmux(13, 0, 1),
            Node::Copy,
            Node::Cmux(12, 0, 1),
            Node::Copy,
            Node::Cmux(11, 0, 1),
            Node::Copy,
            Node::Cmux(10, 0, 1),
            Node::Copy,
            Node::Cmux(9, 0, 1),
            Node::Copy,
            Node::Cmux(8, 0, 1),
            Node::Copy,
            Node::Cmux(7, 0, 1),
            Node::Copy,
            Node::Cmux(6, 0, 1),
            Node::Copy,
            Node::Cmux(5, 0, 1),
            Node::Copy,
            Node::Cmux(4, 0, 1),
            Node::Copy,
            Node::Cmux(3, 0, 1),
            Node::Copy,
            Node::Cmux(2, 0, 1),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B30(BitCircuit::new(
        [
            Node::Cmux(30, 1, 0),
            Node::Cmux(30, 0, 1),
            Node::Copy,
            Node::Cmux(29, 1, 0),
            Node::Copy,
            Node::Cmux(28, 1, 0),
            Node::Copy,
            Node::Cmux(27, 1, 0),
            Node::Copy,
            Node::Cmux(26, 1, 0),
            Node::Copy,
            Node::Cmux(25, 1, 0),
            Node::Copy,
            Node::Cmux(24, 1, 0),
            Node::Copy,
            Node::Cmux(23, 1, 0),
            Node::Copy,
            Node::Cmux(22, 1, 0),
            Node::Copy,
            Node::Cmux(21, 1, 0),
            Node::Copy,
            Node::Cmux(20, 1, 0),
            Node::Copy,
            Node::Cmux(19, 1, 0),
            Node::Copy,
            Node::Cmux(18, 1, 0),
            Node::Copy,
            Node::Cmux(17, 1, 0),
            Node::Copy,
            Node::Cmux(16, 1, 0),
            Node::Copy,
            Node::Cmux(15, 1, 0),
            Node::Copy,
            Node::Cmux(14, 1, 0),
            Node::Copy,
            Node::Cmux(13, 1, 0),
            Node::Copy,
            Node::Cmux(12, 1, 0),
            Node::Copy,
            Node::Cmux(11, 1, 0),
            Node::Copy,
            Node::Cmux(10, 1, 0),
            Node::Copy,
            Node::Cmux(9, 1, 0),
            Node::Copy,
            Node::Cmux(8, 1, 0),
            Node::Copy,
            Node::Cmux(7, 1, 0),
            Node::Copy,
            Node::Cmux(6, 1, 0),
            Node::Copy,
            Node::Cmux(5, 1, 0),
            Node::Copy,
            Node::Cmux(4, 1, 0),
            Node::Copy,
            Node::Cmux(3, 1, 0),
            Node::Cmux(2, 1, 0),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B31(BitCircuit::new(
        [
            Node::Cmux(31, 1, 0),
            Node::Cmux(31, 0, 1),
            Node::Copy,
            Node::Cmux(30, 1, 0),
            Node::Copy,
            Node::Cmux(29, 1, 0),
            Node::Copy,
            Node::Cmux(28, 1, 0),
            Node::Copy,
            Node::Cmux(27, 1, 0),
            Node::Copy,
            Node::Cmux(26, 1, 0),
            Node::Copy,
            Node::Cmux(25, 1, 0),
            Node::Copy,
            Node::Cmux(24, 1, 0),
            Node::Copy,
            Node::Cmux(23, 1, 0),
            Node::Copy,
            Node::Cmux(22, 1, 0),
            Node::Copy,
            Node::Cmux(21, 1, 0),
            Node::Copy,
            Node::Cmux(20, 1, 0),
            Node::Copy,
            Node::Cmux(19, 1, 0),
            Node::Copy,
            Node::Cmux(18, 1, 0),
            Node::Copy,
            Node::Cmux(17, 1, 0),
            Node::Copy,
            Node::Cmux(16, 1, 0),
            Node::Copy,
            Node::Cmux(15, 1, 0),
            Node::Copy,
            Node::Cmux(14, 1, 0),
            Node::Copy,
            Node::Cmux(13, 1, 0),
            Node::Copy,
            Node::Cmux(12, 1, 0),
            Node::Copy,
            Node::Cmux(11, 1, 0),
            Node::Copy,
            Node::Cmux(10, 1, 0),
            Node::Copy,
            Node::Cmux(9, 1, 0),
            Node::Copy,
            Node::Cmux(8, 1, 0),
            Node::Copy,
            Node::Cmux(7, 1, 0),
            Node::Copy,
            Node::Cmux(6, 1, 0),
            Node::Copy,
            Node::Cmux(5, 1, 0),
            Node::Copy,
            Node::Cmux(4, 1, 0),
            Node::Copy,
            Node::Cmux(3, 1, 0),
            Node::Cmux(2, 1, 0),
            Node::None,
        ],
        2,
    )),
]);
